wandb_Api_key: "10989cf7d666f7d3bfcc31c6185448bda1a19767" #Wandb_API_Key (Environment Variable)
wandb_resume: False   #Resume Training
wandb_run_id: None  #Previous Run ID for Resuming , None if starting new run
wandb_run: "Wandb_test"   #Name of wandb run
wandb_project: "MLRC_Synboost"  #wandb project name
pre_epoch: 0    #Previous epoch Number to resume training
epochs: 13      #No. of epochs to run 
name: "latest"  #file Name of the resuming/starting run
best_epoch: 12  #best epoch number in wandb for testing